# Generated by Django 2.0.7 on 2018-10-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0003_auto_20181011_1107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfans',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userfans',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='userfans',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='fans',
        ),
        migrations.DeleteModel(
            name='UserFans',
        ),
    ]
