# Generated by Django 2.0.7 on 2018-10-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0004_auto_20181011_1139'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='用户表',
        ),
    ]
