# Generated by Django 2.0.7 on 2018-07-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0002_student2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student2',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
