# Generated by Django 2.0.7 on 2018-10-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0004_auto_20181003_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
