# Generated by Django 2.0.7 on 2018-10-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0006_auto_20181003_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='csid',
            field=models.ForeignKey(default=1, on_delete=None, to='ll.classes'),
            preserve_default=False,
        ),
    ]
