# Generated by Django 2.0.7 on 2018-10-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0007_student_csid'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='classesToTeacher',
            field=models.ManyToManyField(to='ll.teacher'),
        ),
    ]
