# Generated by Django 2.0.7 on 2018-10-05 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0008_classes_classestoteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='csid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ll.classes'),
        ),
    ]
